"""Initial schema

Revision ID: d0c30b7fa6b8
Revises: 
Create Date: 2026-08-12 14:00:46.535954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c30b7fa6b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('ix_workers_worker_code'), 'workers', ['worker_code'], unique=True)
    op.create_table('approved_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'leave_date', name='uq_worker_leave_date')
    )
    op.create_index(op.f('ix_approved_leaves_id'), 'approved_leaves', ['id'], unique=False)
    op.create_index(op.f('ix_approved_leaves_leave_date'), 'approved_leaves', ['leave_date'], unique=False)
    op.create_index(op.f('ix_approved_leaves_worker_id'), 'approved_leaves', ['worker_id'], unique=False)
    op.create_table('overtime_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('approved_hours', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'work_date', name='uq_worker_overtime_date')
    )
    op.create_index(op.f('ix_overtime_approvals_id'), 'overtime_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_overtime_approvals_work_date'), 'overtime_approvals', ['work_date'], unique=False)
    op.create_index(op.f('ix_overtime_approvals_worker_id'), 'overtime_approvals', ['worker_id'], unique=False)
    op.create_table('payable_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('pay_period_id', sa.String(length=50), nullable=False),
    sa.Column('rostered_hours', sa.Float(), nullable=False),
    sa.Column('actual_worked_hours', sa.Float(), nullable=False),
    sa.Column('payable_hours', sa.Float(), nullable=False),
    sa.Column('approved_overtime_hours', sa.Float(), nullable=False),
    sa.Column('unapproved_overtime_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'work_date', 'pay_period_id', name='uq_worker_date_period')
    )
    op.create_index(op.f('ix_payable_results_id'), 'payable_results', ['id'], unique=False)
    op.create_index(op.f('ix_payable_results_pay_period_id'), 'payable_results', ['pay_period_id'], unique=False)
    op.create_index(op.f('ix_payable_results_work_date'), 'payable_results', ['work_date'], unique=False)
    op.create_index(op.f('ix_payable_results_worker_id'), 'payable_results', ['worker_id'], unique=False)
    op.create_table('punches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('punch_timestamp', sa.DateTime(), nullable=False),
    sa.Column('punch_type', sa.String(length=10), nullable=False),
    sa.Column('raw_device_id', sa.String(length=50), nullable=True),
    sa.Column('is_deduplicated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_punches_id'), 'punches', ['id'], unique=False)
    op.create_index(op.f('ix_punches_punch_timestamp'), 'punches', ['punch_timestamp'], unique=False)
    op.create_index(op.f('ix_punches_worker_id'), 'punches', ['worker_id'], unique=False)
    op.create_table('shift_rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('break_minutes', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_rosters_id'), 'shift_rosters', ['id'], unique=False)
    op.create_index(op.f('ix_shift_rosters_work_date'), 'shift_rosters', ['work_date'], unique=False)
    op.create_index(op.f('ix_shift_rosters_worker_id'), 'shift_rosters', ['worker_id'], unique=False)
    op.create_table('compliance_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payable_result_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('pay_period_id', sa.String(length=50), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payable_result_id'], ['payable_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_flags_id'), 'compliance_flags', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_flags_pay_period_id'), 'compliance_flags', ['pay_period_id'], unique=False)
    op.create_index(op.f('ix_compliance_flags_payable_result_id'), 'compliance_flags', ['payable_result_id'], unique=False)
    op.create_index(op.f('ix_compliance_flags_work_date'), 'compliance_flags', ['work_date'], unique=False)
    op.create_index(op.f('ix_compliance_flags_worker_id'), 'compliance_flags', ['worker_id'], unique=False)
    op.create_table('exception_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payable_result_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('pay_period_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payable_result_id'], ['payable_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_records_id'), 'exception_records', ['id'], unique=False)
    op.create_index(op.f('ix_exception_records_pay_period_id'), 'exception_records', ['pay_period_id'], unique=False)
    op.create_index(op.f('ix_exception_records_payable_result_id'), 'exception_records', ['payable_result_id'], unique=False)
    op.create_index(op.f('ix_exception_records_work_date'), 'exception_records', ['work_date'], unique=False)
    op.create_index(op.f('ix_exception_records_worker_id'), 'exception_records', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exception_records_worker_id'), table_name='exception_records')
    op.drop_index(op.f('ix_exception_records_work_date'), table_name='exception_records')
    op.drop_index(op.f('ix_exception_records_payable_result_id'), table_name='exception_records')
    op.drop_index(op.f('ix_exception_records_pay_period_id'), table_name='exception_records')
    op.drop_index(op.f('ix_exception_records_id'), table_name='exception_records')
    op.drop_table('exception_records')
    op.drop_index(op.f('ix_compliance_flags_worker_id'), table_name='compliance_flags')
    op.drop_index(op.f('ix_compliance_flags_work_date'), table_name='compliance_flags')
    op.drop_index(op.f('ix_compliance_flags_payable_result_id'), table_name='compliance_flags')
    op.drop_index(op.f('ix_compliance_flags_pay_period_id'), table_name='compliance_flags')
    op.drop_index(op.f('ix_compliance_flags_id'), table_name='compliance_flags')
    op.drop_table('compliance_flags')
    op.drop_index(op.f('ix_shift_rosters_worker_id'), table_name='shift_rosters')
    op.drop_index(op.f('ix_shift_rosters_work_date'), table_name='shift_rosters')
    op.drop_index(op.f('ix_shift_rosters_id'), table_name='shift_rosters')
    op.drop_table('shift_rosters')
    op.drop_index(op.f('ix_punches_worker_id'), table_name='punches')
    op.drop_index(op.f('ix_punches_punch_timestamp'), table_name='punches')
    op.drop_index(op.f('ix_punches_id'), table_name='punches')
    op.drop_table('punches')
    op.drop_index(op.f('ix_payable_results_worker_id'), table_name='payable_results')
    op.drop_index(op.f('ix_payable_results_work_date'), table_name='payable_results')
    op.drop_index(op.f('ix_payable_results_pay_period_id'), table_name='payable_results')
    op.drop_index(op.f('ix_payable_results_id'), table_name='payable_results')
    op.drop_table('payable_results')
    op.drop_index(op.f('ix_overtime_approvals_worker_id'), table_name='overtime_approvals')
    op.drop_index(op.f('ix_overtime_approvals_work_date'), table_name='overtime_approvals')
    op.drop_index(op.f('ix_overtime_approvals_id'), table_name='overtime_approvals')
    op.drop_table('overtime_approvals')
    op.drop_index(op.f('ix_approved_leaves_worker_id'), table_name='approved_leaves')
    op.drop_index(op.f('ix_approved_leaves_leave_date'), table_name='approved_leaves')
    op.drop_index(op.f('ix_approved_leaves_id'), table_name='approved_leaves')
    op.drop_table('approved_leaves')
    op.drop_index(op.f('ix_workers_worker_code'), table_name='workers')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
